# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    #base_path: '../../public/bundles/fosckeditor/'
    #js_path:   '../../public/bundles/fosckeditor/ckeditor.js'
    configs:
        main_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', '-', 'Link', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Table', '-', 'Styles', 'Format','-', 'Source'] }